### ISSUE TITLE
rails doesn't see provided dockerized postgresql

### ISSUE THREAD

**Issue by dpneumo** [basecamp/omakub#217]
**Windows 10 Pro version 22H2**
**VMworkstation Pro**
	Ubuntu 24.04 - Fresh install
```	
        wget -qO- https://omakub.org/install | bash
	# Choices: Rails, Postgresql

	sudo apt install libpq-dev postgresql-client-16 postgresql-client-common

	rails new dogapp -d postgresql
	cd dogapp
	bundle install
	rails generate scaffold Dog name:string breed:string

        # Use psql to create postgresql user: dogapp. But
	psql -U postgres  # Fails
```
**error msg:**
```
        psql: error: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
```

```
         rails db:migrate  # Fails
```
**error msg:**
```
	bin/rails aborted!
	ActiveRecord::ConnectionNotEstablished: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: 
	No such file or directory (ActiveRecord::ConnectionNotEstablished)
	Is the server running locally and accepting connections on that socket?
```
**lazydocker shows:**
```
	Containers: running postgres16 ..% 127.0.0.1:5432->5432/tcp
	Logs: 2024-07-15 17:08:46.504 UTC [236] LOG:  invalid length of startup packet
	      ... multiple similar entries ...
```
**database.yml (comment lines removed)**
```
	default: &default
	  adapter: postgresql
	  encoding: unicode
	  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

	development:
	  <<: *default
	  database: dogapp_development
          username: dogapp
          password: dogapp

	test:
	  <<: *default
	  database: dogapp_test
          username: dogapp
          password: dogapp

	production:
	  <<: *default
	  database: dogapp_production
	  username: dogapp
	  password: <%= ENV["DOGAPP_DATABASE_PASSWORD"] %
```
Checking for the socket presence:
```
lsa /var/run/postgresql:
	"/var/run/postgresql": No such file or directory (os error 2)
# lsa /var/run confirms the postgresql folder is missing
```
This is the first time I have used dockerized postgresql so it seems likely that I have missed something fundamental but I cannot identify what that is. Any suggestions? Or is this something that needs to be fixed?
